apiVersion: v1
kind: Secret
metadata:
  name: frontend-secret
type: Opaque
stringData:
  GEMINI_API_KEY: "AIzaSyAYx0N2LPoTxBxLn6GQKG03t_kmdFMq2pY"
  PAYHERE_MERCHANT_SECRET: "MTIyNzg2NjMxMTE1MDAzNTI4NzgyNzgzNjU5NTYzMjQ5ODQwNTY1OA=="
